import React from 'react';
import styles from "./Layout.module.css";
import Head from 'next/dist/shared/lib/head';
import Link from "next/link";


const Layout = ({ children, title="Pochoclo-Time", movies }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Link href="/">
        <img src="https://cdn-icons-png.flaticon.com/512/73/73312.png" alt="movie icon" width="100px" />
        </Link>
      </header>
      <main className={styles.main}>
      {children}
      </main>
      <footer className={styles.footer}>
        Upgrade Hub 2022 - part time febrero
      </footer>
      </div>
  )
};

export default Layout