import React from 'react';
import styles from "./Layout.module.css";
import Head from 'next/dist/shared/lib/head';


const Layout = ({ children, title="Pochoclo-Time" }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <img src="./logo.png" alt="movie icon" width="80px" />
      </header>
      <main className={styles.main}>
      {children}
      </main>
      <footer className={styles.footer}>
        Upgrade Hub 2022
      </footer>
      </div>
  )
};

export default Layout